export const KNOWN_CPUID_FEATURES: readonly string[] = [
  "X64",
  "SSE",
  "SSE2",
  "SSE3",
  "SSSE3",
  "SSE4_1",
  "SSE4_2",
  "AVX",
  "AVX2",
  "FMA",
  "BMI1",
  "BMI2",
  "AES",
  "PCLMULQDQ",
  "POPCNT",
  "LZCNT",
  "SHA",
  "AVX512F",
  "AVX512VL",
  "AVX512BW",
  "AVX512DQ",
  "AVX512CD",
  "AVX512_VBMI",
  "AVX512_VBMI2",
  "AVX512_VNNI",
  "AVX512_BITALG",
  "AVX512_VPOPCNTDQ"
];

export const formatCpuidLabel = (name: string): string => {
  if (name === "X64") return "x86-64";
  if (name.startsWith("AVX512_")) return `AVX-512 ${name.slice("AVX512_".length).replaceAll("_", " ")}`;
  if (name.startsWith("AVX10_")) return `AVX10 ${name.slice("AVX10_".length).replaceAll("_", " ")}`;
  if (/^SSE4_[12]$/.test(name)) return name.replace("_", ".");
  return name;
};

// Sources: Intel SDM, vol. 2A/3C (https://intel.com/content/www/us/en/developer/articles/
// technical/intel-sdm.html); AMD64 Architecture Programmer's Manual (https://amd.com/en/
// support/tech-docs.html); iced-x86 CpuidFeature enum (https://github.com/icedland/iced/
// blob/master/src/rust/iced-x86/src/enums.rs). The enum is the source of the exact IDs.
const CPUID_DESCRIPTIONS: Record<string, string> = {
  INTEL8086: "Instruction available on the original Intel 8086 and later compatible CPUs.",
  INTEL8086_ONLY: "Instruction variant supported only by the original Intel 8086.",
  INTEL186: "Instruction available on the Intel 80186 and later compatible CPUs.",
  INTEL286: "Instruction available on the Intel 80286 and later compatible CPUs.",
  INTEL286_ONLY: "Instruction variant supported only by the Intel 80286.",
  INTEL386: "Instruction available on the Intel 80386 and later compatible CPUs.",
  INTEL386_ONLY: "Instruction variant supported only by the Intel 80386.",
  INTEL386_A0_ONLY: "Early 80386 A0-B0 stepping instruction (XBTS or IBTS).",
  INTEL486: "Instruction available on the Intel 486 and later compatible CPUs.",
  INTEL486_A_ONLY: "Early Intel 486 A-stepping form of CMPXCHG.",
  UMOV: "UMOV instructions implemented by the 80386 and Intel 486.",
  IA64: "Intel IA-64 (Itanium) instruction, not the x86-64 ISA.",
  X64: "x86-64 long mode (64-bit registers and addressing).",
  ADX: "Multi-precision integer addition with independent carry chains (ADCX/ADOX).",
  AES: "AES-NI crypto instructions (AES rounds).",
  AVX: "Advanced Vector Extensions (VEX encoding, 256-bit YMM registers).",
  AVX2: "AVX2 integer 256-bit SIMD extensions (incl. gathers).",
  AVX512_4FMAPS: "AVX-512 four-register fused multiply-accumulate for Knights Mill.",
  AVX512_4VNNIW: "AVX-512 four-register integer dot-product for Knights Mill.",
  AVX512_BF16: "AVX-512 conversion and dot-product operations for bfloat16 values.",
  AVX512_BITALG: "AVX-512 BITALG (bit algorithms).",
  AVX512_IFMA: "AVX-512 integer fused multiply-add for 52-bit limbs.",
  AVX512_VBMI: "AVX-512 Vector Byte Manipulation Instructions.",
  AVX512_VBMI2: "AVX-512 VBMI2 (additional byte manipulation).",
  AVX512_VNNI: "AVX-512 VNNI (integer dot-product for ML).",
  AVX512_VP2INTERSECT: "AVX-512 vector pair intersection comparison instructions.",
  AVX512_VPOPCNTDQ: "AVX-512 VPOPCNTDQ (vector popcount).",
  AVX512BW: "AVX-512 Byte/Word instructions.",
  AVX512CD: "AVX-512 Conflict Detection (CD).",
  AVX512DQ: "AVX-512 Doubleword/Quadword instructions.",
  AVX512ER: "AVX-512 exponential and reciprocal vector instructions for Xeon Phi.",
  AVX512F: "AVX-512 Foundation (512-bit ZMM registers).",
  AVX512PF: "AVX-512 prefetch instructions for Xeon Phi.",
  AVX512VL: "AVX-512 Vector Length extensions (128/256-bit forms).",
  BMI1: "Bit Manipulation Instructions 1 (e.g., ANDN, BEXTR).",
  BMI2: "Bit Manipulation Instructions 2 (e.g., MULX, PDEP/PEXT).",
  CET_IBT: "Control-flow Enforcement Technology indirect branch tracking (ENDBR).",
  CET_SS: "Control-flow Enforcement Technology shadow-stack instructions.",
  CL1INVMB: "Intel Single-Chip Computer cache-line invalidation instruction.",
  CLDEMOTE: "Demotes a cache line toward a more distant cache level.",
  CLFLUSHOPT: "Optimized, weakly ordered cache-line flush instruction.",
  CLFSH: "CLFLUSH cache-line flush instruction.",
  CLWB: "Writes back a cache line without invalidating it.",
  CLZERO: "AMD instruction that zeros an entire cache line.",
  CMOV: "Conditional move instructions.",
  CMPXCHG16B: "Atomic 16-byte compare-and-exchange instruction.",
  CPUID: "CPUID instruction support; the RFLAGS.ID bit can be toggled.",
  CX8: "CMPXCHG8B atomic 8-byte compare-and-exchange instruction.",
  D3NOW: "AMD 3DNow! packed single-precision SIMD extension.",
  D3NOWEXT: "Extended AMD 3DNow! SIMD instructions.",
  OSS: "SGX operating-system support indicator used by SGX instructions.",
  ENQCMD: "Enqueues a command to a device work queue (ENQCMD/ENQCMDS).",
  F16C: "Half-precision floating-point conversion instructions.",
  FMA: "FMA3 fused multiply-add (floating point).",
  FMA4: "AMD four-operand fused multiply-add instructions.",
  FPU: "x87 floating-point unit instructions (8087 and later).",
  FPU287: "x87 instructions requiring an 80287 or later coprocessor.",
  FPU287XL_ONLY: "x87 instruction specific to the 80287XL coprocessor.",
  FPU387: "x87 instructions requiring an 80387 or later coprocessor.",
  FPU387SL_ONLY: "x87 instruction specific to the 80387SL coprocessor.",
  FSGSBASE: "Read and write the FS and GS segment-base registers from user mode.",
  FXSR: "FXSAVE and FXRSTOR extended floating-point/SIMD state management.",
  CYRIX_D3NOW: "Cyrix and AMD Geode GX/LX 3DNow! instructions.",
  GFNI: "Galois-field arithmetic instructions for byte vectors.",
  HLE: "Intel Hardware Lock Elision transactional memory prefixes.",
  HLE_or_RTM: "Instruction usable with either HLE or RTM transactional memory.",
  INVEPT: "Invalidates Intel EPT translation-cache entries for virtualization.",
  INVPCID: "Invalidates TLB entries selected by process-context identifier.",
  INVVPID: "Invalidates Intel VPID translation-cache entries for virtualization.",
  LWP: "AMD Lightweight Profiling instructions.",
  LZCNT: "Leading zero count (ABM/LZCNT).",
  MCOMMIT: "AMD instruction that commits memory pages for a memory region.",
  MMX: "MMX packed integer SIMD instructions using MM registers.",
  MONITOR: "MONITOR/MWAIT address-monitor and wait instructions.",
  MONITORX: "AMD MONITORX/MWAITX monitor and timed-wait instructions.",
  MOVBE: "Loads or stores an integer while reversing its byte order.",
  MOVDIR64B: "Directly moves 64 bytes from memory to memory.",
  MOVDIRI: "Directly stores an integer to memory.",
  MPX: "Intel Memory Protection Extensions bounds-register instructions.",
  MSR: "Read/write model-specific register instructions.",
  MULTIBYTENOP: "Multi-byte NOP encodings used for instruction padding.",
  PADLOCK_ACE: "VIA PadLock Advanced Cryptography Engine instructions.",
  PADLOCK_PHE: "VIA PadLock hash-engine instructions.",
  PADLOCK_PMM: "VIA PadLock Montgomery multiplier instructions.",
  PADLOCK_RNG: "VIA PadLock hardware random-number generator instructions.",
  PAUSE: "Spin-wait hint instruction for busy-wait loops.",
  PCLMULQDQ: "Carry-less multiply (GF(2) multiply; used in GCM/CRC).",
  PCOMMIT: "Deprecated persistent-memory cache-line commit instruction.",
  PCONFIG: "Configures platform-protected memory settings.",
  PKU: "Protection keys for user-space memory pages.",
  POPCNT: "Population count instruction.",
  PREFETCHW: "Prefetches data into cache with intent to write.",
  PREFETCHWT1: "Prefetches data with a write-through cache hint.",
  PTWRITE: "Writes a value to the Intel Processor Trace packet stream.",
  RDPID: "Reads the processor identifier from IA32_TSC_AUX.",
  RDPMC: "Reads a performance-monitoring counter.",
  RDPRU: "Reads an AMD processor register from user mode.",
  RDRAND: "Returns a hardware-generated random value.",
  RDSEED: "Returns entropy suitable for seeding a deterministic random generator.",
  RDTSCP: "Reads the timestamp counter and IA32_TSC_AUX in an ordered form.",
  RTM: "Intel Restricted Transactional Memory instructions (XBEGIN/XEND/XABORT).",
  SEP: "Fast system-call instructions SYSENTER and SYSEXIT.",
  SGX1: "Intel Software Guard Extensions enclave instructions.",
  SHA: "SHA extensions (SHA1/SHA256 rounds).",
  SKINIT: "AMD secure startup instruction.",
  SKINIT_or_SVM: "Instruction usable with AMD SKINIT or Secure Virtual Machine support.",
  SMAP: "Supervisor Mode Access Prevention instructions (STAC/CLAC).",
  SMX: "Intel Safer Mode Extensions trusted-execution instructions.",
  SSE: "Streaming SIMD Extensions (128-bit SIMD instructions).",
  SSE2: "SSE2 SIMD (128-bit integer + double-precision); baseline on x86-64.",
  SSE3: "SSE3 extensions (mostly SIMD horizontal/complex ops).",
  SSE4_1: "SSE4.1 SIMD extensions (dot products, blends, etc.).",
  SSE4_2: "SSE4.2 SIMD extensions (string/CRC-related instructions).",
  SSE4A: "AMD SSE4a extensions, including EXTRQ and INSERTQ.",
  SSSE3: "Supplemental SSE3 (byte-shuffle and other SIMD extensions).",
  SVM: "AMD Secure Virtual Machine virtualization instructions.",
  SEV_ES: "AMD Secure Encrypted Virtualization with encrypted guest register state.",
  SYSCALL: "SYSCALL and SYSRET fast system-call instructions.",
  TBM: "AMD Trailing Bit Manipulation instructions.",
  TSC: "Timestamp Counter read instruction (RDTSC).",
  VAES: "VEX/EVEX encoded AES vector instructions.",
  VMX: "Intel Virtual Machine Extensions instructions.",
  VPCLMULQDQ: "VEX/EVEX encoded carry-less polynomial vector multiplication.",
  WAITPKG: "User-mode wait package instructions (UMONITOR, UMWAIT, TPAUSE).",
  WBNOINVD: "Writes back modified cache lines without disabling caching.",
  XOP: "AMD XOP vector instruction encoding and instruction set.",
  XSAVE: "Extended processor-state save and restore instructions.",
  XSAVEC: "XSAVE variant that compacts the saved state area.",
  XSAVEOPT: "XSAVE variant that skips state components already in their initial state.",
  XSAVES: "Supervisor-aware compacted extended-state save instruction.",
  SEV_SNP: "AMD Secure Nested Paging for SEV-protected virtual machines.",
  SERIALIZE: "Serializes instruction execution before continuing.",
  TSXLDTRK: "Suspends and resumes TSX load-address tracking.",
  INVLPGB: "AMD invalidates translation-cache entries by guest address.",
  AMX_BF16: "Intel Advanced Matrix Extensions bfloat16 tile dot products.",
  AMX_TILE: "Intel Advanced Matrix Extensions tile configuration and data operations.",
  AMX_INT8: "Intel Advanced Matrix Extensions 8-bit integer tile dot products.",
  CYRIX_FPU: "Cyrix and AMD Geode GX/LX floating-point instructions.",
  CYRIX_SMM: "Cyrix system-management instructions such as SVDC and RSDC.",
  CYRIX_SMINT: "Cyrix SMINT 0F38 system-management instruction.",
  CYRIX_SMINT_0F7E: "Cyrix SMINT 0F7E instruction used by early 6x86 CPUs.",
  CYRIX_SHR: "Cyrix system-management register instructions RDSHR and WRSHR.",
  CYRIX_DDI: "Cyrix Device Debug Interface instructions such as CPU_READ and CPU_WRITE.",
  CYRIX_EMMI: "Cyrix Extended MMX instruction extension.",
  CYRIX_DMI: "Cyrix Debug Management Interface instructions DMINT and RDM.",
  CENTAUR_AIS: "Centaur Advanced Instruction Set instructions (ALTINST).",
  MOV_TR: "Moves to or from obsolete test registers TR3-TR7.",
  SMM: "System Management Mode return instruction (RSM).",
  TDX: "Intel Trust Domain Extensions instruction set for confidential VMs.",
  KL: "Intel Key Locker key-management instructions.",
  AESKLE: "Key Locker AES key-load instruction support.",
  WIDE_KL: "Key Locker support for wide (256-bit) encrypted key handles.",
  UINTR: "Intel user-mode interrupt instructions.",
  HRESET: "Intel history-reset instruction for branch-prediction state.",
  AVX_VNNI: "AVX vector neural-network integer dot-product instructions.",
  PADLOCK_GMI: "VIA PadLock Galois-field multiplier instructions.",
  FRED: "Intel Flexible Return and Event Delivery instructions.",
  LKGS: "Loads a kernel GS-base value from memory.",
  AVX512_FP16: "AVX-512 half-precision floating-point arithmetic and conversion.",
  UDBG: "Undocumented Intel user-debug-register instructions RDUDBG and WRUDBG.",
  KNC: "Intel Knights Corner Xeon Phi instruction set.",
  PADLOCK_UNDOC: "Undocumented VIA PadLock instruction.",
  RMPQUERY: "AMD SEV-SNP Reverse Map Table query instruction.",
  RAO_INT: "Relaxed atomic integer operations.",
  PREFETCHITI: "Prefetches instruction-stream data into cache.",
  AMX_FP16: "Intel AMX half-precision floating-point tile operations.",
  CMPCCXADD: "Compares, conditionally updates, and atomically adds an integer value.",
  AVX_IFMA: "AVX integer fused multiply-add for 52-bit limbs.",
  AVX_NE_CONVERT: "AVX neural-network numeric conversion instructions.",
  AVX_VNNI_INT8: "AVX VNNI dot-product operations with 8-bit integer inputs.",
  MSRLIST: "Read and write a list of model-specific registers.",
  WRMSRNS: "Writes a model-specific register without serializing execution.",
  AMX_COMPLEX: "Intel AMX complex-number tile dot-product instructions.",
  SHA512: "SHA-512 message-schedule and round instructions.",
  SM3: "Chinese SM3 hash message-schedule and round instructions.",
  SM4: "Chinese SM4 block-cipher round instructions.",
  TSE: "Intel Total Store Order enforcement instructions.",
  AVX_VNNI_INT16: "AVX VNNI dot-product operations with 16-bit integer inputs."
};

export const describeCpuidFeature = (name: string): string => {
  const known = CPUID_DESCRIPTIONS[name];
  if (known) return known;
  return "No description is available for this instruction requirement.";
};

