// Instruction semantics: Intel SDM Vol. 2 (individual mnemonic entries), Vol. 3 (VMX),
// https://www.intel.com/content/www/us/en/developer/articles/technical/intel-sdm.html
// AMD APM Vol. 3 (SVM instructions): https://docs.amd.com/v/u/en-US/24594_3.37
// These are descriptive groups, not evidence of execution or intent.
export const SPECIAL_INSTRUCTION_CATEGORIES = {
  syscall: ["Direct syscall", "Enters an OS service handler; the service number and function require register context."],
  privileged: ["Kernel privilege", "Requires CPU privileges; administrator rights alone do not suffice."],
  "io-privilege": ["I/O privilege", "Access depends on IOPL and, for port I/O, I/O permissions."],
  trap: ["Trap / interrupt", "Software interrupt or explicit exception; not evidence of malicious code."],
  virtualization: ["Virtualization", "Controls virtual machines or their state; CPU mode and hypervisor configuration govern execution."],
  hypercall: ["Hypervisor call", "Can transfer control to a hypervisor; the operation and calling convention require context."],
  "cpu-query": ["CPU capabilities", "Queries processor features or enabled extended state; often used to select compatible code paths."],
  timing: ["Timing / counters", "Reads timestamps or performance counters; useful for profiling, but alone does not prove anti-debugging."],
  "system-state": ["System state", "Accesses processor control, debug registers or descriptor tables; exposes low-level OS interaction."],
  "cache-tlb": ["Cache / address translation", "Manages cached data or address translations; relevant to coherency, persistence and memory management."],
  "hardware-security": ["Hardware security", "Uses CPU access protections, enclaves or confidential-computing controls; presence does not prove that protection is enabled."],
  transaction: ["Transactional memory", "Controls speculative memory transactions and their abort paths; presence does not prove transactions succeed."]
} as const;

export type PeSpecialInstructionCategory = keyof typeof SPECIAL_INSTRUCTION_CATEGORIES;

export const SPECIAL_INSTRUCTION_CATALOG: Readonly<Record<
  string, readonly [PeSpecialInstructionCategory, string]
>> = {
  SYSCALL: ["syscall", "Transfers to an OS handler using model-specific register configuration; inspect registers to identify the service."],
  SYSENTER: ["syscall", "Enters an OS handler through the SYSENTER registers; used by fast system-call gateways."],
  "INT 0x2E": ["syscall", "Windows historically uses interrupt 2Eh as a system-service gateway; the service depends on register values."],
  INT: ["trap", "Invokes a software interrupt vector; its meaning depends on the OS and installed handler."],
  INT1: ["trap", "Raises a debug exception; can expose debugger or exception-handler paths."],
  INT3: ["trap", "Raises a breakpoint exception; also commonly appears in code padding."],
  INTO: ["trap", "Raises an overflow exception if the overflow flag is set; reveals arithmetic exception handling."],
  UD0: ["trap", "Deliberately raises an invalid-opcode exception; may implement unreachable-code or exception paths."],
  UD1: ["trap", "Deliberately raises an invalid-opcode exception; may implement unreachable-code or exception paths."],
  UD2: ["trap", "Deliberately raises an invalid-opcode exception; commonly marks failed assumptions or unreachable code."],
  CLI: ["io-privilege", "Clears the interrupt flag, or its virtual counterpart where supported; relevant to interrupt-sensitive code."],
  STI: ["io-privilege", "Sets the interrupt flag, or its virtual counterpart where supported; affects interrupt delivery."],
  IN: ["io-privilege", "Reads from an I/O port into the accumulator; indicates direct device or platform interaction."],
  INSB: ["io-privilege", "Reads bytes from an I/O port into memory; REP can repeat the device transfer."],
  INSW: ["io-privilege", "Reads words from an I/O port into memory; REP can repeat the device transfer."],
  INSD: ["io-privilege", "Reads doublewords from an I/O port into memory; REP can repeat the device transfer."],
  OUT: ["io-privilege", "Writes the accumulator to an I/O port; indicates direct device or platform interaction."],
  OUTSB: ["io-privilege", "Writes memory bytes to an I/O port; REP can repeat the device transfer."],
  OUTSW: ["io-privilege", "Writes memory words to an I/O port; REP can repeat the device transfer."],
  OUTSD: ["io-privilege", "Writes memory doublewords to an I/O port; REP can repeat the device transfer."],
  VMXON: ["virtualization", "Enters Intel VMX operation; identifies hypervisor initialization code."],
  VMXOFF: ["virtualization", "Leaves Intel VMX operation; identifies hypervisor teardown code."],
  VMCLEAR: ["virtualization", "Clears a VM control structure's launch state and makes it inactive; prepares VM state management."],
  VMPTRLD: ["virtualization", "Selects the current Intel VM control structure; identifies which guest state will be managed."],
  VMPTRST: ["virtualization", "Stores the pointer to the current Intel VM control structure; exposes VM state bookkeeping."],
  VMREAD: ["virtualization", "Reads a field of the VM control structure; inspects guest state or virtualization controls."],
  VMWRITE: ["virtualization", "Writes a VM control structure field; configures guest state or virtualization controls."],
  VMLAUNCH: ["virtualization", "Performs VM entry using a clear VM control structure; starts guest execution."],
  VMRESUME: ["virtualization", "Performs VM entry using a launched VM control structure; resumes guest execution."],
  VMFUNC: ["virtualization", "Invokes an enabled VM function from guest context without a VM exit; can switch EPT mappings."],
  INVEPT: ["virtualization", "Invalidates translations derived from Intel extended page tables; maintains guest-memory mappings."],
  INVVPID: ["virtualization", "Invalidates translations associated with virtual processor identifiers; manages cached guest translations."],
  VMRUN: ["virtualization", "Starts or resumes an AMD SVM guest using its VM control block; marks a guest-entry path."],
  VMLOAD: ["virtualization", "Loads selected processor state from an AMD VM control block; supports guest context switching."],
  VMSAVE: ["virtualization", "Saves selected processor state to an AMD VM control block; supports guest context switching."],
  STGI: ["virtualization", "Sets AMD's global interrupt flag; controls interrupt delivery around virtualization transitions."],
  CLGI: ["virtualization", "Clears AMD's global interrupt flag; controls interrupt delivery around virtualization transitions."],
  INVLPGA: ["virtualization", "Invalidates an address translation for an AMD address-space identifier; manages guest TLB state."],
  VMCALL: ["hypercall", "In Intel VMX guest operation, causes a VM exit; often used for hypervisor services. Other modes have different semantics."],
  VMMCALL: ["hypercall", "AMD's instruction for requesting a VMM service; the intercept configuration and register arguments determine behavior."],
  CPUID: ["cpu-query", "Reads a selected processor-information leaf; can query features, topology or a hypervisor interface."],
  XGETBV: ["cpu-query", "Reads an extended control register; commonly checks which vector register state the OS enables."],
  RDTSC: ["timing", "Reads the timestamp counter without full serialization; timing interpretation depends on surrounding instructions."],
  RDTSCP: ["timing", "Reads the timestamp counter and TSC_AUX with partial ordering; useful for timing and processor-context identification."],
  RDPMC: ["timing", "Reads a selected performance counter; counter configuration and OS permissions determine its meaning and availability."],
  RDMSR: ["system-state", "Reads a model-specific register selected by ECX; the register index identifies the platform feature being inspected."],
  WRMSR: ["system-state", "Writes a model-specific register selected by ECX; may configure CPU, security or system-call behavior."],
  "MOV CR": ["system-state", "Transfers to or from a control register; the register and direction reveal inspection or changes to CPU execution and paging."],
  "MOV DR": ["system-state", "Transfers to or from a debug register; exposes hardware breakpoint and debug-control access."],
  SGDT: ["system-state", "Stores the global descriptor-table register; exposes segmentation metadata, subject to UMIP restrictions."],
  SIDT: ["system-state", "Stores the interrupt descriptor-table register; exposes interrupt-table metadata, subject to UMIP restrictions."],
  SLDT: ["system-state", "Stores the local descriptor-table selector; exposes segmentation state, subject to UMIP restrictions."],
  STR: ["system-state", "Stores the task-register selector; exposes task-state metadata, subject to UMIP restrictions."],
  SMSW: ["system-state", "Reads the machine status word from CR0; exposes CPU mode state, subject to UMIP restrictions."],
  LGDT: ["system-state", "Loads the global descriptor-table register; changes the CPU's segmentation-table reference."],
  LIDT: ["system-state", "Loads the interrupt descriptor-table register; changes where the CPU finds interrupt and exception handlers."],
  LLDT: ["system-state", "Loads the local descriptor-table selector; changes the current local segmentation context."],
  LTR: ["system-state", "Loads the task register; selects the task-state segment used by OS mechanisms."],
  LMSW: ["system-state", "Loads low control bits of CR0; associated with legacy CPU mode setup."],
  CLTS: ["system-state", "Clears CR0's task-switched flag; used in managing floating-point state ownership."],
  XSETBV: ["system-state", "Writes an extended control register; configures enabled processor state components."],
  CLFLUSH: ["cache-tlb", "Writes back and invalidates a cache line; relevant to cache management and timing-sensitive code."],
  CLFLUSHOPT: ["cache-tlb", "Writes back and invalidates a cache line with relaxed ordering; inspect fences for ordering requirements."],
  CLWB: ["cache-tlb", "Writes back a cache line that may remain cached; relevant to persistent-memory updates."],
  INVD: ["cache-tlb", "Invalidates internal caches without writing back dirty data; a sensitive platform-management operation."],
  WBINVD: ["cache-tlb", "Writes back and invalidates caches; used by low-level platform and memory-management code."],
  WBNOINVD: ["cache-tlb", "Writes back modified cache lines without invalidating them; used in platform cache management."],
  INVLPG: ["cache-tlb", "Invalidates translation entries for a linear address; typically follows a page-table change."],
  INVPCID: ["cache-tlb", "Invalidates translations for a selected process-context scope; supports address-space management."],
  ENDBR32: ["hardware-security", "Marks a valid 32-bit indirect-branch target for CET IBT; presence does not establish that IBT is active."],
  ENDBR64: ["hardware-security", "Marks a valid 64-bit indirect-branch target for CET IBT; presence does not establish that IBT is active."],
  RDPKRU: ["hardware-security", "Reads protection-key permissions for user pages; exposes in-process memory-access policy."],
  WRPKRU: ["hardware-security", "Writes protection-key permissions for user pages; can change access without changing page tables."],
  ENCLS: ["hardware-security", "Dispatches a privileged SGX operation selected by EAX; used to manage enclave resources."],
  ENCLU: ["hardware-security", "Dispatches an SGX user operation selected by EAX; can enter, resume or exit enclave execution."],
  ENCLV: ["hardware-security", "Dispatches an SGX virtualization operation selected by EAX; relevant to enclave support in guests."],
  RDSSPD: ["hardware-security", "Reads the shadow-stack pointer; indicates CET shadow-stack-aware code."],
  RDSSPQ: ["hardware-security", "Reads the shadow-stack pointer; indicates CET shadow-stack-aware code."],
  INCSSPD: ["hardware-security", "Advances the shadow-stack pointer; can support unwinding protected return state."],
  INCSSPQ: ["hardware-security", "Advances the shadow-stack pointer; can support unwinding protected return state."],
  RSTORSSP: ["hardware-security", "Restores a shadow-stack pointer from a restore token; supports protected stack switching."],
  SAVEPREVSSP: ["hardware-security", "Saves a restore token for the previous shadow stack; supports protected stack switching."],
  WRSSD: ["hardware-security", "Writes a doubleword to shadow-stack memory when enabled; exposes explicit protected-stack maintenance."],
  WRSSQ: ["hardware-security", "Writes a quadword to shadow-stack memory when enabled; exposes explicit protected-stack maintenance."],
  WRUSSD: ["hardware-security", "Writes a doubleword to a user shadow stack from supervisor code; supports OS shadow-stack management."],
  WRUSSQ: ["hardware-security", "Writes a quadword to a user shadow stack from supervisor code; supports OS shadow-stack management."],
  SETSSBSY: ["hardware-security", "Marks a supervisor shadow stack busy; supports CET stack activation."],
  CLRSSBSY: ["hardware-security", "Clears a supervisor shadow-stack busy flag; supports CET stack lifecycle management."],
  XBEGIN: ["transaction", "Starts a restricted transaction and specifies an abort target; inspect both transactional and fallback paths."],
  XEND: ["transaction", "Attempts to commit the active restricted transaction; marks a transactional region's end."],
  XABORT: ["transaction", "Explicitly aborts a restricted transaction with an immediate code; exposes a deliberate fallback path."],
  XTEST: ["transaction", "Tests whether execution is inside a transactional region; supports transaction-aware branching."],
  XSUSLDTRK: ["transaction", "Suspends transaction load-address tracking; changes which reads participate in conflict detection."],
  XRESLDTRK: ["transaction", "Resumes transaction load-address tracking; restores tracking after XSUSLDTRK."],
  HLT: ["privileged", "Halts instruction execution until a qualifying event; commonly used in kernel idle or stop paths."],
  SYSRET: ["privileged", "Returns from a fast system-call handler; exposes the transition back to less-privileged code."],
  SYSEXIT: ["privileged", "Returns to less-privileged code using SYSENTER-related state; marks an OS service-return path."],
  RSM: ["privileged", "Resumes execution from System Management Mode; identifies firmware system-management code."],
  // Intel SDM Vol. 2; HRESET/SEAMCALL also appear in Intel's instruction extensions reference:
  // https://cdrdv2-public.intel.com/671368/architecture-instruction-set-extensions-programming-reference.pdf
  STAC: ["hardware-security", "Sets the AC flag, allowing supervisor access to user pages when SMAP applies; identifies temporary access-policy changes."],
  CLAC: ["hardware-security", "Clears the AC flag, restoring SMAP restrictions when enabled; often closes a supervisor user-memory access window."],
  SWAPGS: ["system-state", "Exchanges GS base with the kernel GS-base MSR; commonly switches thread or CPU-local context at kernel boundaries."],
  XSAVES: ["system-state", "Saves selected user and supervisor extended processor state in compacted form; relevant to OS context switching."],
  XSAVES64: ["system-state", "Uses the 64-bit form of XSAVES to save selected extended processor state; relevant to OS context switching."],
  XRSTORS: ["system-state", "Restores selected user and supervisor extended processor state; relevant to OS context switching."],
  XRSTORS64: ["system-state", "Uses the 64-bit form of XRSTORS to restore selected extended processor state; relevant to OS context switching."],
  SYSRETQ: ["privileged", "Returns from a fast system-call handler to 64-bit code; exposes a kernel-to-user transition."],
  SYSEXITQ: ["privileged", "Uses the 64-bit SYSEXIT form to return to less-privileged code; marks an OS service-return path."],
  ENQCMDS: ["privileged", "Submits a command to a device queue with supervisor-specified identity; exposes accelerator or device work submission."],
  HRESET: ["system-state", "Resets enabled processor history selected by EAX; can isolate task history used by hardware feedback."],
  PCONFIG: ["hardware-security", "Dispatches platform configuration selected by EAX; supported leaves can configure memory-encryption keys."],
  SEAMCALL: ["hardware-security", "Calls an Intel TDX module entry point from the host; exposes confidential-VM management operations."],
  // AMD APM Vol. 3: reverse-map-table operations for SEV-SNP.
  RMPUPDATE: ["hardware-security", "Updates a reverse-map-table entry; changes ownership or state of a physical page for SEV-SNP."],
  PSMASH: ["hardware-security", "Splits a large reverse-map-table entry into smaller entries; supports finer-grained SEV-SNP page management."]
};
