import { cpSync, existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const projectRoot = resolve(__dirname, "..");
const distDir = join(projectRoot, "dist");

mkdirSync(distDir, { recursive: true });

const staticFiles = ["index.html", "style.css"];

for (const file of staticFiles) {
  const sourcePath = join(projectRoot, file);
  const targetPath = join(distDir, file);
  cpSync(sourcePath, targetPath);
}

const icedX86Dir = join(projectRoot, "node_modules", "iced-x86");
if (existsSync(icedX86Dir)) {
  const icedOutDir = join(distDir, "vendor", "iced-x86");
  mkdirSync(icedOutDir, { recursive: true });

  cpSync(join(icedX86Dir, "iced_x86_bg.wasm"), join(icedOutDir, "iced_x86_bg.wasm"));

  const nodeEntry = readFileSync(join(icedX86Dir, "iced_x86.js"), "utf8");
  const preamble = `// Generated by scripts/copy-static.mjs\n` + `const module = { exports: {} };\n`;
  const withoutUtilRequire = nodeEntry.replace(
    "const { TextDecoder, TextEncoder } = require(`util`);",
    "const { TextDecoder, TextEncoder } = globalThis;"
  );

  const nodeBootstrap = "const path = require('path').join(__dirname, 'iced_x86_bg.wasm');";
  const bootstrapIndex = withoutUtilRequire.lastIndexOf(nodeBootstrap);
  if (bootstrapIndex === -1) {
    throw new Error("iced-x86 wrapper format changed; could not locate wasm bootstrap section");
  }

  const webBootstrap = `const wasmUrl = new URL("iced_x86_bg.wasm", import.meta.url);\n` +
    `const response = await fetch(wasmUrl);\n` +
    `if (!response.ok) {\n` +
    `    throw new Error(\`Failed to load iced-x86 wasm: \${response.status} \${response.statusText}\`);\n` +
    `}\n` +
    `const bytes = new Uint8Array(await response.arrayBuffer());\n` +
    `const wasmModule = new WebAssembly.Module(bytes);\n` +
    `const wasmInstance = new WebAssembly.Instance(wasmModule, imports);\n` +
    `wasm = wasmInstance.exports;\n` +
    `module.exports.__wasm = wasm;\n` +
    `\n` +
    `export default module.exports;\n` +
    `export const Code = module.exports.Code;\n` +
    `export const CpuidFeature = module.exports.CpuidFeature;\n` +
    `export const DecoderOptions = module.exports.DecoderOptions;\n` +
    `export const Mnemonic = module.exports.Mnemonic;\n` +
    `export const getIcedFeatures = module.exports.getIcedFeatures;\n` +
    `\n` +
    `const DecoderExport = module.exports.Decoder;\n` +
    `const InstructionExport = module.exports.Instruction;\n` +
    `const OpCodeInfoExport = module.exports.OpCodeInfo;\n` +
    `export { DecoderExport as Decoder, InstructionExport as Instruction, OpCodeInfoExport as OpCodeInfo };\n`;

  const webEntry =
    preamble +
    withoutUtilRequire.slice(0, bootstrapIndex) +
    webBootstrap;

  writeFileSync(join(icedOutDir, "iced_x86.js"), webEntry, "utf8");
}
