// Field order and typed-handle encodings are generated by dotnet/runtime.
// https://github.com/dotnet/runtime/blob/v10.0.0/src/coreclr/tools/Common/Internal/Metadata/NativeFormat/NativeFormatReaderGen.cs
// https://github.com/dotnet/runtime/blob/v10.0.0/src/coreclr/tools/Common/Internal/Metadata/NativeFormat/NativeFormatReaderCommonGen.cs
export type NativeFormatField = readonly [
  name: string, encoding: "unsigned" | "byte" | "bytes" | "handle" |
    "handles" | "unsigneds" | "signeds", handleType?: number
];

export const nativeFormatSchemas: Readonly<Record<number, readonly NativeFormatField[]>> = {
  0x01: [["element", "handle"], ["rank", "unsigned"],
    ["sizes", "unsigneds"], ["lowerBounds", "signeds"]],
  0x02: [["type", "handle"]],
  0x22: [["flags", "unsigned"], ["name", "handle", 0x1a], ["type", "handle"],
    ["semantics", "handles", 0x2a], ["attributes", "handles", 0x21]],
  0x23: [["flags", "unsigned"], ["name", "handle", 0x1a], ["signature", "handle", 0x24],
    ["defaultValue", "handle"], ["offset", "unsigned"], ["attributes", "handles", 0x21]],
  0x24: [["type", "handle"]],
  0x25: [["signature", "handle", 0x2b]],
  0x26: [["number", "unsigned"], ["flags", "unsigned"], ["kind", "unsigned"],
    ["name", "handle", 0x1a], ["constraints", "handles"], ["attributes", "handles", 0x21]],
  0x28: [["flags", "unsigned"], ["implementationFlags", "unsigned"], ["name", "handle", 0x1a],
    ["signature", "handle", 0x2b], ["parameters", "handles", 0x31],
    ["genericParameters", "handles", 0x26], ["attributes", "handles", 0x21]],
  0x2a: [["attributes", "unsigned"], ["method", "handle", 0x28]],
  0x2b: [["callingConvention", "unsigned"], ["genericParameterCount", "unsigned"],
    ["returnType", "handle"], ["parameters", "handles"], ["varArgParameters", "handles"]],
  0x2c: [["number", "unsigned"]],
  0x2d: [["isOptional", "byte"], ["modifier", "handle"], ["type", "handle"]],
  0x2f: [["parent", "handle"], ["name", "handle", 0x1a], ["types", "handles", 0x3a],
    ["forwarders", "handles", 0x3b], ["children", "handles", 0x2f]],
  0x30: [["parent", "handle"], ["name", "handle", 0x1a]],
  0x31: [["flags", "unsigned"], ["sequence", "unsigned"], ["name", "handle", 0x1a],
    ["defaultValue", "handle"], ["attributes", "handles", 0x21]],
  0x32: [["type", "handle"]],
  0x33: [["flags", "unsigned"], ["name", "handle", 0x1a], ["signature", "handle", 0x34],
    ["semantics", "handles", 0x2a], ["defaultValue", "handle"], ["attributes", "handles", 0x21]],
  0x34: [["callingConvention", "unsigned"], ["type", "handle"], ["parameters", "handles"]],
  0x37: [["element", "handle"]],
  0x38: [["flags", "unsigned"], ["name", "handle", 0x1a], ["hashAlgorithm", "unsigned"],
    ["major", "unsigned"], ["minor", "unsigned"], ["build", "unsigned"], ["revision", "unsigned"],
    ["publicKey", "bytes"], ["culture", "handle", 0x1a], ["rootNamespace", "handle", 0x2f],
    ["entryPoint", "handle", 0x36], ["globalType", "handle", 0x3a],
    ["attributes", "handles", 0x21], ["moduleName", "handle", 0x1a], ["mvid", "bytes"],
    ["moduleAttributes", "handles", 0x21]],
  0x39: [["flags", "unsigned"], ["name", "handle", 0x1a], ["major", "unsigned"],
    ["minor", "unsigned"], ["build", "unsigned"], ["revision", "unsigned"],
    ["publicKeyOrToken", "bytes"], ["culture", "handle", 0x1a]],
  0x3a: [["flags", "unsigned"], ["baseType", "handle"], ["namespace", "handle", 0x2f],
    ["name", "handle", 0x1a], ["size", "unsigned"], ["packingSize", "unsigned"],
    ["enclosingType", "handle", 0x3a], ["nestedTypes", "handles", 0x3a],
    ["methods", "handles", 0x28], ["fields", "handles", 0x23],
    ["properties", "handles", 0x33], ["events", "handles", 0x22],
    ["genericParameters", "handles", 0x26], ["interfaces", "handles"],
    ["attributes", "handles", 0x21]],
  0x3c: [["genericType", "handle"], ["arguments", "handles"]],
  0x3d: [["parent", "handle"], ["name", "handle", 0x1a]],
  0x3e: [["signature", "handle"]],
  0x3f: [["number", "unsigned"]]
};
